In [ ]:
# numpy - > it is an open source library that is used for scientific calculations

In [ ]:
# Why numpy is better than list?
# 1. it is homogeneous data type while list is hetrogeneous
# 2. it takes less memory while list takes more memory
# 3. it takes less execution time while list takes more execution time
# 4. it has more functionalitity than list

In [ ]:
# !pip install numpy

In [ ]:
import numpy as np


In [ ]:
a = [1, 45, 78, 90]
type(a)

list

In [ ]:
b = np.array(a)
type(b)

numpy.ndarray

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b= np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# how can we check shape, size and dimensions of the array?

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(a)
print("total rows and columns", a.shape)
print("total number of elements", a.size)
print("total dimensions", a.ndim)

total rows and columns (3, 3)
total number of elements 9
total dimensions 2


In [ ]:
# how can we create user defined array?

In [ ]:
a= []
size = int(input("Enter size : "))
for i in range(size):
    val = int(input("Enter value : "))
    a.append(val)
a = np.array(a)
a

Enter size : 3
Enter value : 12
Enter value : 34
Enter value : 56


array([12, 34, 56])

In [ ]:
# tuple to array
a= (1,2,3)
a = np.array(a)
a

array([1, 2, 3])

In [ ]:
# @title FUNCTIONS IN PYTHON

In [ ]:
# 1. zeros() -> it will create an array in which all elements are zero either in
# one dimentional or multi dimensional
import numpy as np
a = np.zeros(4)
print(a)
a = np.zeros((3,4))
print(f"\n{a}\n")
b = np.zeros((3,4,5))
b

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
# 2. ones() -> it will create an array in which all elements are 1 either in
# one dimentional or multi dimensional
a = np.ones(3)
print(a)
a = np.ones((3,4))
a

[1. 1. 1.]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# 3. eye() -> it will create an array in ehich all the diagonal positional
#  elements are 1 and rest are 0
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 4. diag() -> it will customize the diagonal positional elements and  rest are 0
a = [23,54,1,6]
b = np.diag(a)
b

array([[23,  0,  0,  0],
       [ 0, 54,  0,  0],
       [ 0,  0,  1,  0],
       [ 0,  0,  0,  6]])

In [ ]:
# RANDOM MODULE
  # a. randint() ---> it will create random numbers in a given range
  # syntax - np.random.randint(start, end, total_values)
a= np.random.randint(1,10,3)
a

array([3, 4, 8])

In [ ]:
# b. rand()---> it will create an array in which all the values will be in range
#  of 0 to 1
a = np.random.rand(3)
a

array([0.17325716, 0.0295001 , 0.40153662])

In [ ]:
# c. seed() ---> it will fix the random generated values
np.random.seed(10)
a = np.random.randint(1,10,3)
a

array([5, 1, 2])

In [ ]:
# VIEW VS COPY
# view means modification in original data
# copy means modification in duplicate data which will not reflect in the orignal
# data
a = np.array([1,2,3,4,5])
print(a)
b = a[1:4]
b[:] = 0

print(b)
print(a)


[1 2 3 4 5]
[0 0 0]
[1 0 0 0 5]


In [ ]:
a = np.array([1,2,3,4,5])
print(a)
b = a[1:4].copy()
b[:] = 0

print(b)
print(a)

[1 2 3 4 5]
[0 0 0]
[1 2 3 4 5]


In [ ]:
# RESHAPING OF ARRAY
# n(rows) * n(columns) = n(total_elements)


In [ ]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a=a.reshape(5,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
# a = a.reshape(5,5)


In [ ]:
a>10

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [ ]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [ ]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
a = np.arange(1,16).reshape(5,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.sum(a, axis = 0)

array([35, 40, 45])

In [ ]:
np.sum(a, axis = 1)

array([ 6, 15, 24, 33, 42])

In [ ]:
print(np.sum(a))

120


In [ ]:
a**2

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144],
       [169, 196, 225]])

In [ ]:
a**3

array([[   1,    8,   27],
       [  64,  125,  216],
       [ 343,  512,  729],
       [1000, 1331, 1728],
       [2197, 2744, 3375]])

In [ ]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a.dot(b)   #for matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
# # Unique() ---> it will return 3 arrays
# 1. arr ---> unique elements of array
# 2. return_index = True ---> it will return index of unique elements
# 3. return_counts = True ---> it will return count of unique elements


In [ ]:
a = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(a, return_index=True, return_counts=True)

(array([1, 2, 3, 4, 5, 6]),
 array([ 0,  2,  4,  6,  8, 10]),
 array([2, 2, 2, 2, 2, 2]))

In [ ]:
# linspace() ---> it will return an array in which gaps of values will be equal
# syntax:- np.linspace(start, end, total_values)


In [14]:
import numpy as np
a = np.linspace(1,10,5)
a


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
# # Hstack() and vstack()
# hstack()---> it will combine arrays horizontally
# vstack()---> it will combine  arrays vertically

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])

np.hstack((a,b,c))

np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Questions

In [ ]:
# Q.1  Write statement to import numpy?
# Ans. import numpy as np

In [ ]:
import numpy as np

In [ ]:
# Q.2 Create an array using numpy?
# Ans:-

a = np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [ ]:
# Q.3 Create an array of 10 random integers?
# Ans:-

a = np.random.randint(1, 10, 10)
print(a)

[9 1 5 2 4 8 5 4 6 9]


In [ ]:
# Q.4 Create an array of elements from 10-20?
# Ans:-

a = np.arange(10, 20)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
# Q.5 Create an array which contains value 5, 10 times?
# Ans:-
a = np.ones(10)
print(a*5)


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
# Q.6 Create a one dimensional array and convert that into 3*3 matrix?
# Ans:-
a = np.arange(1,10)
print(a)
a = a.reshape(3,3)
print(a)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Q.7 Create a 2D array of size 3*3 but all the elements should be between 0 to 1?
a = np.random.rand(3,3)
print(a)

[[0.87804153 0.58092499 0.40627475]
 [0.79604162 0.43862448 0.68823332]
 [0.4270683  0.91649088 0.53344153]]


In [ ]:
# Q.8 Concatenate 2D array horizontally and vertically?
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])
print("Horizontal stack:-")
print(np.hstack((a,b,c)))
print("\nVertical stack:-")
print(np.vstack((a,b,c)))

Horizontal stack:-
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Vertical stack:-
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:

# import numpy as np



# expenses = []

# def date_exp(date):
#     for date in expenses:
#         print(expenses['amount'])

# def add_expense(date, category, amount):
#     expenses.append({'date': date, 'category': category, 'amount': amount})

# def show_total():
#     total = sum(expense['amount'] for expense in expenses)
#     print(f"Total Expense: {total}")

# while True:
#     try:
#         choice = input("1. Add Expense\n2. Show expenses\n3. Show Total\n4. Exit\nEnter choice: ")

#         if choice == '1':
#             date = input("Enter date (DD-MM-YYYY): ")
#             category = input("Enter category: ")
#             amount = float(input("Enter amount: "))
#             add_expense(date, category, amount)

#         elif choice == '2':



#             for items in expenses:
#                 print(items)

#         elif choice == '3':

#             show_total()
#         elif choice == '5':
#             date_exp(input("Enter date (DD-MM-YYYY): "))
#         elif choice == '4':
#             break

#     except ValueError:
#         print("Enter a number !!! ")




In [10]:
data = [
    {'date': '22-12-2024', 'category': 'food', 'amount': 1000},
    {'date': '22-12-2024', 'category': 'travel', 'amount': 2000},
    {'date': '20-12-2024', 'category': 'food', 'amount': 500},
    {'date': '22-12-2024', 'category': 'health', 'amount': 200},

]

def total_sum(key, val):
  sum = 0
  for items in data:
    if items[key] == val:
        print(items)
        sum += items['amount']
  return sum

# print()
print(f"sum = {total_sum('date', '22-12-2024')}")


{'date': '22-12-2024', 'category': 'food', 'amount': 1000}
{'date': '22-12-2024', 'category': 'travel', 'amount': 2000}
{'date': '22-12-2024', 'category': 'health', 'amount': 200}
sum = 3200
